dataset: oxfordiiitpet
data_root: ./data

# resnet18, resnet50, resnest14d, resnest26d, mlp
model_name: resnest26d
pretrained: True
num_classes: 37
image_size: 224

num_workers: 4

batch_size: 32
num_epochs: 2

# adam, sgd, adamw, sam, muon
optimizer: adamw
lr: 0.001
weight_decay: 0.0005
momentum: 0.9

# steplr, reducelronplateau
scheduler: steplr
step_size: 10
gamma: 0.1
patience: 5
factor: 0.1

log_dir: ./runs/oxfordiiitpet
use_wandb: false
use_amp: False